# Generated by Django 4.2.3 on 2023-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_user', '0002_portaluser_groups_portaluser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='consumer_number',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
