# Generated by Django 4.2.3 on 2023-08-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_user', '0003_alter_portaluser_consumer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaluser',
            name='login_count',
        ),
    ]
