# Generated by Django 4.2.3 on 2023-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_user', '0004_remove_portaluser_login_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='consumer_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
