# Generated by Django 4.2.3 on 2023-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_user', '0005_alter_portaluser_consumer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
