# Generated by Django 4.2.3 on 2023-09-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_user', '0006_alter_portaluser_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portaluser',
            old_name='consumer_number',
            new_name='consumer_or_staff_id',
        ),
        migrations.RemoveField(
            model_name='portaluser',
            name='staff_id',
        ),
    ]
